#!/bin/bash
set -e -u

#######################################
# Configuration
#######################################

# What video player do you want to use?
PLAYER=mpv

# What format will be recognized as possible embeded videos
FORMATS="youtube.com \.mp4 \.avi \.webm \.ogv rtmp:// \.mp3 \.ogm \.flac \
         \.mkv \.m3u8 magnet:"

# Should we launch some tests?
DEBUG=false

# Torrent player command
P2PLAYER="peerflix -k"

#######################################
# Extensions
#######################################
# Used to perform domain specific actions, just define a function whose name
# is the target domain and it will be executed with maximum priority.

livecoding.tv() {
    curl -s "$1" |\
    tr '"' '\n'  |\
    grep -a rtmp |\
    xargs "$PLAYER"
}

kat.cr() {
    curl -s --compressed "$1" |\
    tr '"' '\n'               |\
    grep -a "^magnet:"        |\
    head -1                   |\
    xargs $P2PLAYER
}

#######################################
# Internals
#######################################

domain() {
    sed -n '\|http|s|^https\?://\([^/]\+\)/.*$|\1|p' <<< "$1"
}

scheme() {
    sed -n "\|://|s|^\([^:]\+\)://.*$|\1|p" <<< "$1"
}

get_videos() {
    content="$(curl --compressed -s "$1")"

    for format in $FORMATS ; do
        echo "$content" |\
        tr "'\"" "\n\n" |\
        grep -a "$format"
    done
}

normalize_url() {
    sed "\|^[^/:][^:]\+$|s|^|/| ; \|^/|s|^|$(scheme "$1")://$(domain "$1")|"
}

# Some debug tests, not exactly unittests but useful for debugging
tests() {
scheme "http://home/cym13/.home.html/"
domain "http://home/cym13/.home.html/"

normalize_url "http://my_site.com/thingy/" <<EOF
/a/video.mp4
video.mp4
http://my_site.com/a/video.mp4
EOF

}

main() {
    if $DEBUG ; then
        tests
    fi

    # No arguments given
    if [[ -z "${@:-''}" ]] ; then
        echo "Usage: see URLS..."
        exit 1
    fi

    for i in `seq $#` ; do
        url="$1"

        # Try the extension function
        if "$(domain "$url")" "$url" 2>/dev/null ; then
            shift
            continue
        fi

        # Try with the default player
        if "$PLAYER" "$url" ; then
            shift
            continue
        fi

        # If it isn't a url, maybe it's a magnet link
        # Either way we quit here
        if [[ -z "$(scheme "$url")" ]] ; then
            $P2PLAYER "$url"
            shift
            continue
        fi

        # Try automatically finding embeded urls
        local urls="$(get_videos "$url")"

        if [[ -z "$urls" ]] ; then
            shift
            continue
        fi

        uniq <<<"$urls"      |\
        normalize_url "$url" |\
        tr "\n" "\0"         |\
        xargs -0 "$PLAYER"

        shift
    done
}

main "$@"
